#!/usr/bin/env python3
"""Exact verification of the route-overlap extremal claim for unlabeled trees.

For an n-vertex tree T, choose two unordered vertex-pair routes independently
and uniformly (the same route may be chosen twice). Let L_T be the number of
edges in the intersection of the two routes. This script checks, exactly, that
for each threshold k >= 1,

    # {(R1,R2): L_T >= k} <= # {(R1,R2): L_{P_n} >= k}

for every non-isomorphic tree generated by NetworkX, through a requested n.
All counting is integer/exact; no Monte Carlo sampling is used.

Default max_n=13 is deliberately modest and reproducible on an ordinary PC.
Larger values can be requested with --max-n, but enumeration grows quickly.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path
from time import perf_counter

import networkx as nx


def route_edge_masks(T: nx.Graph):
    """Return bit masks for all unordered vertex-pair routes in T."""
    nodes = list(T.nodes())
    edge_index = {frozenset(e): i for i, e in enumerate(T.edges())}
    masks = []
    for i, u in enumerate(nodes):
        for v in nodes[i + 1 :]:
            path = nx.shortest_path(T, u, v)
            mask = 0
            for a, b in zip(path, path[1:]):
                mask |= 1 << edge_index[frozenset((a, b))]
            masks.append(mask)
    return masks


def overlap_histogram(T: nx.Graph) -> Counter:
    """Histogram of L over ordered pairs of routes, including identical routes."""
    masks = route_edge_masks(T)
    hist = Counter()
    for a in masks:
        for b in masks:
            hist[(a & b).bit_count()] += 1
    return hist


def tail_counts(hist: Counter, max_k: int):
    """Return exact counts A_k = # ordered route pairs with L >= k."""
    return {
        k: sum(count for ell, count in hist.items() if ell >= k)
        for k in range(1, max_k + 1)
    }


def path_tail_closed_form(n: int, k: int) -> int:
    """Closed-form A_k(P_n)."""
    if not (1 <= k <= n - 1):
        return 0
    m = n - k + 1
    num = m * (m - 1) * (m * m - m + 1)
    assert num % 6 == 0
    return num // 6


def verify(max_n: int):
    total_trees = 0
    total_route_pairs = 0
    failures = []
    ties_by_n = {}
    per_n = []

    started = perf_counter()

    for n in range(3, max_n + 1):
        p = nx.path_graph(n)
        p_hist = overlap_histogram(p)
        p_tail = tail_counts(p_hist, n - 1)

        for k in range(1, n):
            cf = path_tail_closed_form(n, k)
            if p_tail[k] != cf:
                raise AssertionError(
                    f"Closed-form mismatch for P_{n}, k={k}: raw={p_tail[k]}, formula={cf}"
                )

        count_n = 0
        nonpath_full_ties = 0
        nonpath_threshold_ties = 0
        smallest_nonpath_margin = None
        smallest_nonpath_case = None

        for idx, T in enumerate(nx.generators.nonisomorphic_trees(n)):
            count_n += 1
            total_trees += 1
            hist = overlap_histogram(T)
            tails = tail_counts(hist, n - 1)
            M = n * (n - 1) // 2
            total_route_pairs += M * M

            is_path = nx.is_isomorphic(T, p)
            tied_all_positive = True

            for k in range(1, n):
                margin = p_tail[k] - tails[k]
                if not is_path:
                    if smallest_nonpath_margin is None or margin < smallest_nonpath_margin:
                        smallest_nonpath_margin = margin
                        smallest_nonpath_case = {"tree_index": idx, "k": k, "margin": margin}
                    if margin == 0:
                        nonpath_threshold_ties += 1

                if margin < 0:
                    failures.append(
                        {
                            "n": n,
                            "tree_index": idx,
                            "k": k,
                            "tree_edges": sorted(tuple(sorted(e)) for e in T.edges()),
                            "tree_tail": tails[k],
                            "path_tail": p_tail[k],
                        }
                    )
                    return {
                        "status": "FAILED",
                        "max_n": max_n,
                        "failures": failures,
                    }
                if margin != 0:
                    tied_all_positive = False

            if tied_all_positive and not is_path:
                nonpath_full_ties += 1

        ties_by_n[n] = {"full_distribution_ties": nonpath_full_ties, "individual_threshold_ties": nonpath_threshold_ties}
        per_n.append(
            {
                "n": n,
                "nonisomorphic_trees": count_n,
                "nonpath_full_ties": nonpath_full_ties,
                "nonpath_individual_threshold_ties": nonpath_threshold_ties,
                "smallest_nonpath_margin_seen": smallest_nonpath_margin,
                "smallest_nonpath_margin_case": smallest_nonpath_case,
            }
        )
        print(
            f"n={n:2d}: {count_n:5d} trees; "
            f"non-path threshold ties={nonpath_threshold_ties}; OK"
        )

    elapsed = perf_counter() - started
    return {
        "status": "PASSED",
        "max_n": max_n,
        "total_nonisomorphic_trees_checked": total_trees,
        "total_ordered_route_pairs_evaluated_across_trees": total_route_pairs,
        "nonpath_full_ties_by_n": ties_by_n,
        "per_n": per_n,
        "elapsed_seconds": elapsed,
        "networkx_version": nx.__version__,
        "notes": [
            "Exact integer enumeration; no random sampling.",
            "Routes are unordered endpoint pairs, while route pairs are ordered and sampled independently.",
            "The same route may be selected twice, matching the probability model in the note.",
        ],
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--max-n", type=int, default=13)
    ap.add_argument("--json", type=Path, default=None, help="Optional output JSON path")
    args = ap.parse_args()

    if args.max_n < 3:
        raise SystemExit("--max-n must be at least 3")

    result = verify(args.max_n)
    print(json.dumps(result, indent=2))
    if args.json:
        args.json.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")

    if result["status"] != "PASSED":
        raise SystemExit(1)


if __name__ == "__main__":
    main()
